site_name: PHP-ML - 机器学习PHP库
pages:
  - 首页: index.md
  - 机器学习:
    - 关联性规则学习:
      - Apriori: machine-learning/association/apriori.md
    - 分类:
      - SVC: machine-learning/classification/svc.md
      - KNearestNeighbors: machine-learning/classification/k-nearest-neighbors.md
      - NaiveBayes: machine-learning/classification/naive-bayes.md
    - 回归:
      - LeastSquares: machine-learning/regression/least-squares.md
      - SVR: machine-learning/regression/svr.md
    - 聚类:
      - KMeans: machine-learning/clustering/k-means.md
      - DBSCAN: machine-learning/clustering/dbscan.md
    - 指标:
      - Accuracy: machine-learning/metric/accuracy.md
      - Confusion Matrix: machine-learning/metric/confusion-matrix.md
      - Classification Report: machine-learning/metric/classification-report.md
    - 工作流:
      - Pipeline: machine-learning/workflow/pipeline.md
    - 神经网络:
      - Multilayer Perceptron: machine-learning/neural-network/multilayer-perceptron.md
      - Backpropagation training: machine-learning/neural-network/backpropagation.md
    - 交叉验证:
      - RandomSplit: machine-learning/cross-validation/random-split.md
      - Stratified Random Split: machine-learning/cross-validation/stratified-random-split.md
    - 预处理:
      - Normalization: machine-learning/preprocessing/normalization.md
      - Imputation missing values: machine-learning/preprocessing/imputation-missing-values.md
    - 特征提取:
      - Token Count Vectorizer: machine-learning/feature-extraction/token-count-vectorizer.md
      - Tf-idf Transformer: machine-learning/feature-extraction/tf-idf-transformer.md
    - 数据集:
      - Array Dataset: machine-learning/datasets/array-dataset.md
      - CSV Dataset: machine-learning/datasets/csv-dataset.md
      - Files Dataset: machine-learning/datasets/files-dataset.md
      - Ready to use datasets:
        - Iris: machine-learning/datasets/demo/iris.md
        - Wine: machine-learning/datasets/demo/wine.md
        - Glass: machine-learning/datasets/demo/glass.md
    - 模型管理:
        - Persistency: machine-learning/model-manager/persistency.md
  - 数学:
    - Distance: math/distance.md
    - Matrix: math/matrix.md
    - Set: math/set.md
    - Statistic: math/statistic.md
theme: readthedocs
